apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mosquitto.fullname" . }}-pv
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.mosquitto.persistence.size }}
  accessModes:
    - {{ .Values.mosquitto.persistence.accessMode }}
  hostPath:
    path: {{ .Values.mosquitto.persistence.hostPath }}
  storageClassName: {{ .Values.mosquitto.persistence.storageClass }}