apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mosquitto.fullname" . }}-secret
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
type: Opaque
stringData:
  password_file: |
    {{ .Values.mosquitto.auth.username }}:{{ .Values.mosquitto.auth.password }}