global:
  configMapName: hindalcodev-configmap

# Mosquitto specific configurations
mosquitto:
  deploymentName: mosquitto-deployment
  serviceName: mosquitto-service
  appLabel: mosquitto
  replicaCount: 1

  image:
    repository: eclipse-mosquitto
    tag: 2.0.18

  ports:
  - name: mqtt
    containerPort: 1883
  - name: websocket
    containerPort: 9001

  service:
    type: LoadBalancer
    ports:
    - name: mqtt
      port: 1883
      targetPort: mqtt
      protocol: TCP
    - name: websocket
      port: 9001
      targetPort: websocket
      protocol: TCP

  security:
    fsGroup: 1883
    runAsUser: 1883
    runAsGroup: 1883

  config:
    allowAnonymous: true
    logType:
    - all
    - debug
    connectionMessages: true

  auth:
    username: admin
    password: admin123456

  persistence:
    enabled: true
    storageClass: manual
    size: 1Gi
    accessMode: ReadWriteOnce
    hostPath: /mnt/data

ingress:
  enabled: false
