{{- define "common.service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  selector:
    app: {{ .Values.appLabel }}
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
  {{- end }}
{{- end -}}

{{- define "mosquitto.service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mosquitto.serviceName }}
spec:
  selector:
    app: {{ .Values.mosquitto.appLabel }}
  type: {{ .Values.mosquitto.service.type }}
  ports:
  {{- range .Values.mosquitto.service.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
  {{- end }}
{{- end -}}